// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: testsystem/v1/events.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestStartEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	TestName      string                 `protobuf:"bytes,2,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStartEventRequest) Reset() {
	*x = TestStartEventRequest{}
	mi := &file_testsystem_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStartEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStartEventRequest) ProtoMessage() {}

func (x *TestStartEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStartEventRequest.ProtoReflect.Descriptor instead.
func (*TestStartEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *TestStartEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestStartEventRequest) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *TestStartEventRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TestStartEventRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TestFinishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Status        TestStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=testsystem.v1.TestStatus" json:"status,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // If any
	StackTrace    string                 `protobuf:"bytes,6,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`       // If any
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestFinishEventRequest) Reset() {
	*x = TestFinishEventRequest{}
	mi := &file_testsystem_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestFinishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestFinishEventRequest) ProtoMessage() {}

func (x *TestFinishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestFinishEventRequest.ProtoReflect.Descriptor instead.
func (*TestFinishEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *TestFinishEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestFinishEventRequest) GetStatus() TestStatus {
	if x != nil {
		return x.Status
	}
	return TestStatus_UNKNOWN
}

func (x *TestFinishEventRequest) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TestFinishEventRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *TestFinishEventRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TestFinishEventRequest) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

type TestStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        TestStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=testsystem.v1.TestStatus" json:"status,omitempty"`
	Attachments   []*Attachment          `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStepRequest) Reset() {
	*x = TestStepRequest{}
	mi := &file_testsystem_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStepRequest) ProtoMessage() {}

func (x *TestStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStepRequest.ProtoReflect.Descriptor instead.
func (*TestStepRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *TestStepRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TestStepRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TestStepRequest) GetStatus() TestStatus {
	if x != nil {
		return x.Status
	}
	return TestStatus_UNKNOWN
}

func (x *TestStepRequest) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type TestStepEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Steps         []*TestStepRequest     `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestStepEventRequest) Reset() {
	*x = TestStepEventRequest{}
	mi := &file_testsystem_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestStepEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestStepEventRequest) ProtoMessage() {}

func (x *TestStepEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestStepEventRequest.ProtoReflect.Descriptor instead.
func (*TestStepEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *TestStepEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestStepEventRequest) GetSteps() []*TestStepRequest {
	if x != nil {
		return x.Steps
	}
	return nil
}

var File_testsystem_v1_events_proto protoreflect.FileDescriptor

const file_testsystem_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1atestsystem/v1/events.proto\x12\rtestsystem.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1atestsystem/v1/common.proto\"\x95\x02\n" +
	"\x15TestStartEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x1b\n" +
	"\ttest_name\x18\x02 \x01(\tR\btestName\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12N\n" +
	"\bmetadata\x18\x04 \x03(\v22.testsystem.v1.TestStartEventRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"\x16TestFinishEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.testsystem.v1.TestStatusR\x06status\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12;\n" +
	"\vattachments\x18\x04 \x03(\v2\x19.testsystem.v1.AttachmentR\vattachments\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vstack_trace\x18\x06 \x01(\tR\n" +
	"stackTrace\"\xdd\x01\n" +
	"\x0fTestStepRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.testsystem.v1.TestStatusR\x06status\x12;\n" +
	"\vattachments\x18\x04 \x03(\v2\x19.testsystem.v1.AttachmentR\vattachments\"e\n" +
	"\x14TestStepEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x124\n" +
	"\x05steps\x18\x02 \x03(\v2\x1e.testsystem.v1.TestStepRequestR\x05stepsBR\n" +
	"\x1ecom.stanterprise.testsystem.v1P\x01Z.github.com/stanterprise/proto-go/testsystem/v1b\x06proto3"

var (
	file_testsystem_v1_events_proto_rawDescOnce sync.Once
	file_testsystem_v1_events_proto_rawDescData []byte
)

func file_testsystem_v1_events_proto_rawDescGZIP() []byte {
	file_testsystem_v1_events_proto_rawDescOnce.Do(func() {
		file_testsystem_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testsystem_v1_events_proto_rawDesc), len(file_testsystem_v1_events_proto_rawDesc)))
	})
	return file_testsystem_v1_events_proto_rawDescData
}

var file_testsystem_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_testsystem_v1_events_proto_goTypes = []any{
	(*TestStartEventRequest)(nil),  // 0: testsystem.v1.TestStartEventRequest
	(*TestFinishEventRequest)(nil), // 1: testsystem.v1.TestFinishEventRequest
	(*TestStepRequest)(nil),        // 2: testsystem.v1.TestStepRequest
	(*TestStepEventRequest)(nil),   // 3: testsystem.v1.TestStepEventRequest
	nil,                            // 4: testsystem.v1.TestStartEventRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
	(TestStatus)(0),                // 6: testsystem.v1.TestStatus
	(*Attachment)(nil),             // 7: testsystem.v1.Attachment
}
var file_testsystem_v1_events_proto_depIdxs = []int32{
	5, // 0: testsystem.v1.TestStartEventRequest.start_time:type_name -> google.protobuf.Timestamp
	4, // 1: testsystem.v1.TestStartEventRequest.metadata:type_name -> testsystem.v1.TestStartEventRequest.MetadataEntry
	6, // 2: testsystem.v1.TestFinishEventRequest.status:type_name -> testsystem.v1.TestStatus
	5, // 3: testsystem.v1.TestFinishEventRequest.end_time:type_name -> google.protobuf.Timestamp
	7, // 4: testsystem.v1.TestFinishEventRequest.attachments:type_name -> testsystem.v1.Attachment
	5, // 5: testsystem.v1.TestStepRequest.timestamp:type_name -> google.protobuf.Timestamp
	6, // 6: testsystem.v1.TestStepRequest.status:type_name -> testsystem.v1.TestStatus
	7, // 7: testsystem.v1.TestStepRequest.attachments:type_name -> testsystem.v1.Attachment
	2, // 8: testsystem.v1.TestStepEventRequest.steps:type_name -> testsystem.v1.TestStepRequest
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_testsystem_v1_events_proto_init() }
func file_testsystem_v1_events_proto_init() {
	if File_testsystem_v1_events_proto != nil {
		return
	}
	file_testsystem_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testsystem_v1_events_proto_rawDesc), len(file_testsystem_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testsystem_v1_events_proto_goTypes,
		DependencyIndexes: file_testsystem_v1_events_proto_depIdxs,
		MessageInfos:      file_testsystem_v1_events_proto_msgTypes,
	}.Build()
	File_testsystem_v1_events_proto = out.File
	file_testsystem_v1_events_proto_goTypes = nil
	file_testsystem_v1_events_proto_depIdxs = nil
}
