// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: testsystem/v1/observer/observer.proto

package observer

import (
	events "github.com/stanterprise/proto-go/testsystem/v1/events"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                             // Optional message
	ErrorCode     *int32                 `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"` // Optional error code for failed operations
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_testsystem_v1_observer_observer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_observer_observer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_observer_observer_proto_rawDescGZIP(), []int{0}
}

func (x *AckResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AckResponse) GetErrorCode() int32 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return 0
}

var File_testsystem_v1_observer_observer_proto protoreflect.FileDescriptor

const file_testsystem_v1_observer_observer_proto_rawDesc = "" +
	"\n" +
	"%testsystem/v1/observer/observer.proto\x12\x16testsystem.v1.observer\x1a!testsystem/v1/events/events.proto\"t\n" +
	"\vAckResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\"\n" +
	"\n" +
	"error_code\x18\x03 \x01(\x05H\x00R\terrorCode\x88\x01\x01B\r\n" +
	"\v_error_code2\xc0\t\n" +
	"\x12TestEventCollector\x12_\n" +
	"\n" +
	"MapTestRun\x12,.testsystem.v1.events.MapTestRunEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12e\n" +
	"\x10ReportSuiteBegin\x12,.testsystem.v1.events.SuiteBeginEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12a\n" +
	"\x0eReportSuiteEnd\x12*.testsystem.v1.events.SuiteEndEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12c\n" +
	"\x0fReportTestBegin\x12+.testsystem.v1.events.TestBeginEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12_\n" +
	"\rReportTestEnd\x12).testsystem.v1.events.TestEndEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12c\n" +
	"\x0fReportStepBegin\x12+.testsystem.v1.events.StepBeginEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12_\n" +
	"\rReportStepEnd\x12).testsystem.v1.events.StepEndEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12g\n" +
	"\x11ReportTestFailure\x12-.testsystem.v1.events.TestFailureEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12c\n" +
	"\x0fReportTestError\x12+.testsystem.v1.events.TestErrorEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12a\n" +
	"\x0eReportStdError\x12*.testsystem.v1.events.StdErrorEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12c\n" +
	"\x0fReportStdOutput\x12+.testsystem.v1.events.StdOutputEventRequest\x1a#.testsystem.v1.observer.AckResponse\x12]\n" +
	"\tHeartbeat\x12+.testsystem.v1.events.HeartbeatEventRequest\x1a#.testsystem.v1.observer.AckResponseBd\n" +
	"'com.stanterprise.testsystem.v1.observerP\x01Z7github.com/stanterprise/proto-go/testsystem/v1/observerb\x06proto3"

var (
	file_testsystem_v1_observer_observer_proto_rawDescOnce sync.Once
	file_testsystem_v1_observer_observer_proto_rawDescData []byte
)

func file_testsystem_v1_observer_observer_proto_rawDescGZIP() []byte {
	file_testsystem_v1_observer_observer_proto_rawDescOnce.Do(func() {
		file_testsystem_v1_observer_observer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testsystem_v1_observer_observer_proto_rawDesc), len(file_testsystem_v1_observer_observer_proto_rawDesc)))
	})
	return file_testsystem_v1_observer_observer_proto_rawDescData
}

var file_testsystem_v1_observer_observer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_testsystem_v1_observer_observer_proto_goTypes = []any{
	(*AckResponse)(nil),                    // 0: testsystem.v1.observer.AckResponse
	(*events.MapTestRunEventRequest)(nil),  // 1: testsystem.v1.events.MapTestRunEventRequest
	(*events.SuiteBeginEventRequest)(nil),  // 2: testsystem.v1.events.SuiteBeginEventRequest
	(*events.SuiteEndEventRequest)(nil),    // 3: testsystem.v1.events.SuiteEndEventRequest
	(*events.TestBeginEventRequest)(nil),   // 4: testsystem.v1.events.TestBeginEventRequest
	(*events.TestEndEventRequest)(nil),     // 5: testsystem.v1.events.TestEndEventRequest
	(*events.StepBeginEventRequest)(nil),   // 6: testsystem.v1.events.StepBeginEventRequest
	(*events.StepEndEventRequest)(nil),     // 7: testsystem.v1.events.StepEndEventRequest
	(*events.TestFailureEventRequest)(nil), // 8: testsystem.v1.events.TestFailureEventRequest
	(*events.TestErrorEventRequest)(nil),   // 9: testsystem.v1.events.TestErrorEventRequest
	(*events.StdErrorEventRequest)(nil),    // 10: testsystem.v1.events.StdErrorEventRequest
	(*events.StdOutputEventRequest)(nil),   // 11: testsystem.v1.events.StdOutputEventRequest
	(*events.HeartbeatEventRequest)(nil),   // 12: testsystem.v1.events.HeartbeatEventRequest
}
var file_testsystem_v1_observer_observer_proto_depIdxs = []int32{
	1,  // 0: testsystem.v1.observer.TestEventCollector.MapTestRun:input_type -> testsystem.v1.events.MapTestRunEventRequest
	2,  // 1: testsystem.v1.observer.TestEventCollector.ReportSuiteBegin:input_type -> testsystem.v1.events.SuiteBeginEventRequest
	3,  // 2: testsystem.v1.observer.TestEventCollector.ReportSuiteEnd:input_type -> testsystem.v1.events.SuiteEndEventRequest
	4,  // 3: testsystem.v1.observer.TestEventCollector.ReportTestBegin:input_type -> testsystem.v1.events.TestBeginEventRequest
	5,  // 4: testsystem.v1.observer.TestEventCollector.ReportTestEnd:input_type -> testsystem.v1.events.TestEndEventRequest
	6,  // 5: testsystem.v1.observer.TestEventCollector.ReportStepBegin:input_type -> testsystem.v1.events.StepBeginEventRequest
	7,  // 6: testsystem.v1.observer.TestEventCollector.ReportStepEnd:input_type -> testsystem.v1.events.StepEndEventRequest
	8,  // 7: testsystem.v1.observer.TestEventCollector.ReportTestFailure:input_type -> testsystem.v1.events.TestFailureEventRequest
	9,  // 8: testsystem.v1.observer.TestEventCollector.ReportTestError:input_type -> testsystem.v1.events.TestErrorEventRequest
	10, // 9: testsystem.v1.observer.TestEventCollector.ReportStdError:input_type -> testsystem.v1.events.StdErrorEventRequest
	11, // 10: testsystem.v1.observer.TestEventCollector.ReportStdOutput:input_type -> testsystem.v1.events.StdOutputEventRequest
	12, // 11: testsystem.v1.observer.TestEventCollector.Heartbeat:input_type -> testsystem.v1.events.HeartbeatEventRequest
	0,  // 12: testsystem.v1.observer.TestEventCollector.MapTestRun:output_type -> testsystem.v1.observer.AckResponse
	0,  // 13: testsystem.v1.observer.TestEventCollector.ReportSuiteBegin:output_type -> testsystem.v1.observer.AckResponse
	0,  // 14: testsystem.v1.observer.TestEventCollector.ReportSuiteEnd:output_type -> testsystem.v1.observer.AckResponse
	0,  // 15: testsystem.v1.observer.TestEventCollector.ReportTestBegin:output_type -> testsystem.v1.observer.AckResponse
	0,  // 16: testsystem.v1.observer.TestEventCollector.ReportTestEnd:output_type -> testsystem.v1.observer.AckResponse
	0,  // 17: testsystem.v1.observer.TestEventCollector.ReportStepBegin:output_type -> testsystem.v1.observer.AckResponse
	0,  // 18: testsystem.v1.observer.TestEventCollector.ReportStepEnd:output_type -> testsystem.v1.observer.AckResponse
	0,  // 19: testsystem.v1.observer.TestEventCollector.ReportTestFailure:output_type -> testsystem.v1.observer.AckResponse
	0,  // 20: testsystem.v1.observer.TestEventCollector.ReportTestError:output_type -> testsystem.v1.observer.AckResponse
	0,  // 21: testsystem.v1.observer.TestEventCollector.ReportStdError:output_type -> testsystem.v1.observer.AckResponse
	0,  // 22: testsystem.v1.observer.TestEventCollector.ReportStdOutput:output_type -> testsystem.v1.observer.AckResponse
	0,  // 23: testsystem.v1.observer.TestEventCollector.Heartbeat:output_type -> testsystem.v1.observer.AckResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_testsystem_v1_observer_observer_proto_init() }
func file_testsystem_v1_observer_observer_proto_init() {
	if File_testsystem_v1_observer_observer_proto != nil {
		return
	}
	file_testsystem_v1_observer_observer_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testsystem_v1_observer_observer_proto_rawDesc), len(file_testsystem_v1_observer_observer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testsystem_v1_observer_observer_proto_goTypes,
		DependencyIndexes: file_testsystem_v1_observer_observer_proto_depIdxs,
		MessageInfos:      file_testsystem_v1_observer_observer_proto_msgTypes,
	}.Build()
	File_testsystem_v1_observer_observer_proto = out.File
	file_testsystem_v1_observer_observer_proto_goTypes = nil
	file_testsystem_v1_observer_observer_proto_depIdxs = nil
}
