// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: testsystem/v1/events/events.proto

package events

import (
	common "github.com/stanterprise/proto-go/testsystem/v1/common"
	entities "github.com/stanterprise/proto-go/testsystem/v1/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestBeginEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestCase      *entities.TestCaseRun  `protobuf:"bytes,1,opt,name=test_case,json=testCase,proto3" json:"test_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestBeginEventRequest) Reset() {
	*x = TestBeginEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestBeginEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestBeginEventRequest) ProtoMessage() {}

func (x *TestBeginEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestBeginEventRequest.ProtoReflect.Descriptor instead.
func (*TestBeginEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{0}
}

func (x *TestBeginEventRequest) GetTestCase() *entities.TestCaseRun {
	if x != nil {
		return x.TestCase
	}
	return nil
}

type TestEndEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestCase      *entities.TestCaseRun  `protobuf:"bytes,1,opt,name=test_case,json=testCase,proto3" json:"test_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestEndEventRequest) Reset() {
	*x = TestEndEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestEndEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEndEventRequest) ProtoMessage() {}

func (x *TestEndEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEndEventRequest.ProtoReflect.Descriptor instead.
func (*TestEndEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{1}
}

func (x *TestEndEventRequest) GetTestCase() *entities.TestCaseRun {
	if x != nil {
		return x.TestCase
	}
	return nil
}

type StepBeginEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          *entities.StepRun      `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepBeginEventRequest) Reset() {
	*x = StepBeginEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepBeginEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepBeginEventRequest) ProtoMessage() {}

func (x *StepBeginEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepBeginEventRequest.ProtoReflect.Descriptor instead.
func (*StepBeginEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{2}
}

func (x *StepBeginEventRequest) GetStep() *entities.StepRun {
	if x != nil {
		return x.Step
	}
	return nil
}

type StepEndEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          *entities.StepRun      `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepEndEventRequest) Reset() {
	*x = StepEndEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepEndEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEndEventRequest) ProtoMessage() {}

func (x *StepEndEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEndEventRequest.ProtoReflect.Descriptor instead.
func (*StepEndEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{3}
}

func (x *StepEndEventRequest) GetStep() *entities.StepRun {
	if x != nil {
		return x.Step
	}
	return nil
}

type TestFailureEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TestId         string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	FailureMessage string                 `protobuf:"bytes,2,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	StackTrace     string                 `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attachments    []*common.Attachment   `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	RunId          string                 `protobuf:"bytes,6,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestFailureEventRequest) Reset() {
	*x = TestFailureEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestFailureEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestFailureEventRequest) ProtoMessage() {}

func (x *TestFailureEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestFailureEventRequest.ProtoReflect.Descriptor instead.
func (*TestFailureEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{4}
}

func (x *TestFailureEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestFailureEventRequest) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *TestFailureEventRequest) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *TestFailureEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TestFailureEventRequest) GetAttachments() []*common.Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *TestFailureEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type TestErrorEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StackTrace    string                 `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attachments   []*common.Attachment   `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	RunId         string                 `protobuf:"bytes,6,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestErrorEventRequest) Reset() {
	*x = TestErrorEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestErrorEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestErrorEventRequest) ProtoMessage() {}

func (x *TestErrorEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestErrorEventRequest.ProtoReflect.Descriptor instead.
func (*TestErrorEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{5}
}

func (x *TestErrorEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestErrorEventRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TestErrorEventRequest) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *TestErrorEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TestErrorEventRequest) GetAttachments() []*common.Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *TestErrorEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StdErrorEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TestCaseRunId string                 `protobuf:"bytes,4,opt,name=test_case_run_id,json=testCaseRunId,proto3" json:"test_case_run_id,omitempty"` // Reference to the specific test case run
	RunId         string                 `protobuf:"bytes,5,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdErrorEventRequest) Reset() {
	*x = StdErrorEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdErrorEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdErrorEventRequest) ProtoMessage() {}

func (x *StdErrorEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdErrorEventRequest.ProtoReflect.Descriptor instead.
func (*StdErrorEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{6}
}

func (x *StdErrorEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *StdErrorEventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StdErrorEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StdErrorEventRequest) GetTestCaseRunId() string {
	if x != nil {
		return x.TestCaseRunId
	}
	return ""
}

func (x *StdErrorEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StdOutputEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TestCaseRunId string                 `protobuf:"bytes,4,opt,name=test_case_run_id,json=testCaseRunId,proto3" json:"test_case_run_id,omitempty"` // Reference to the specific test case run
	RunId         string                 `protobuf:"bytes,5,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdOutputEventRequest) Reset() {
	*x = StdOutputEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdOutputEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdOutputEventRequest) ProtoMessage() {}

func (x *StdOutputEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdOutputEventRequest.ProtoReflect.Descriptor instead.
func (*StdOutputEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{7}
}

func (x *StdOutputEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *StdOutputEventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StdOutputEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StdOutputEventRequest) GetTestCaseRunId() string {
	if x != nil {
		return x.TestCaseRunId
	}
	return ""
}

func (x *StdOutputEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type SuiteBeginEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suite         *entities.TestSuiteRun `protobuf:"bytes,1,opt,name=suite,proto3" json:"suite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuiteBeginEventRequest) Reset() {
	*x = SuiteBeginEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuiteBeginEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuiteBeginEventRequest) ProtoMessage() {}

func (x *SuiteBeginEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuiteBeginEventRequest.ProtoReflect.Descriptor instead.
func (*SuiteBeginEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{8}
}

func (x *SuiteBeginEventRequest) GetSuite() *entities.TestSuiteRun {
	if x != nil {
		return x.Suite
	}
	return nil
}

type SuiteEndEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suite         *entities.TestSuiteRun `protobuf:"bytes,1,opt,name=suite,proto3" json:"suite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuiteEndEventRequest) Reset() {
	*x = SuiteEndEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuiteEndEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuiteEndEventRequest) ProtoMessage() {}

func (x *SuiteEndEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuiteEndEventRequest.ProtoReflect.Descriptor instead.
func (*SuiteEndEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{9}
}

func (x *SuiteEndEventRequest) GetSuite() *entities.TestSuiteRun {
	if x != nil {
		return x.Suite
	}
	return nil
}

type HeartbeatEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // Identifier for the source sending the heartbeat
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEventRequest) Reset() {
	*x = HeartbeatEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEventRequest) ProtoMessage() {}

func (x *HeartbeatEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEventRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatEventRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *HeartbeatEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ReportRunStartEventRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	RunId         string                   `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	TestSuites    []*entities.TestSuiteRun `protobuf:"bytes,2,rep,name=test_suites,json=testSuites,proto3" json:"test_suites,omitempty"`
	TotalTests    int32                    `protobuf:"varint,3,opt,name=total_tests,json=totalTests,proto3" json:"total_tests,omitempty"`
	Name          string                   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      map[string]string        `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRunStartEventRequest) Reset() {
	*x = ReportRunStartEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRunStartEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRunStartEventRequest) ProtoMessage() {}

func (x *ReportRunStartEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRunStartEventRequest.ProtoReflect.Descriptor instead.
func (*ReportRunStartEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{11}
}

func (x *ReportRunStartEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReportRunStartEventRequest) GetTestSuites() []*entities.TestSuiteRun {
	if x != nil {
		return x.TestSuites
	}
	return nil
}

func (x *ReportRunStartEventRequest) GetTotalTests() int32 {
	if x != nil {
		return x.TotalTests
	}
	return 0
}

func (x *ReportRunStartEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReportRunStartEventRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TestRunEndEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	FinalStatus   common.TestStatus      `protobuf:"varint,2,opt,name=final_status,json=finalStatus,proto3,enum=testsystem.v1.common.TestStatus" json:"final_status,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestRunEndEventRequest) Reset() {
	*x = TestRunEndEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestRunEndEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestRunEndEventRequest) ProtoMessage() {}

func (x *TestRunEndEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestRunEndEventRequest.ProtoReflect.Descriptor instead.
func (*TestRunEndEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{12}
}

func (x *TestRunEndEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TestRunEndEventRequest) GetFinalStatus() common.TestStatus {
	if x != nil {
		return x.FinalStatus
	}
	return common.TestStatus(0)
}

func (x *TestRunEndEventRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TestRunEndEventRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_testsystem_v1_events_events_proto protoreflect.FileDescriptor

const file_testsystem_v1_events_events_proto_rawDesc = "" +
	"\n" +
	"!testsystem/v1/events/events.proto\x12\x14testsystem.v1.events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!testsystem/v1/common/common.proto\x1a&testsystem/v1/entities/test_case.proto\x1a'testsystem/v1/entities/test_suite.proto\x1a\x1egoogle/protobuf/duration.proto\"Y\n" +
	"\x15TestBeginEventRequest\x12@\n" +
	"\ttest_case\x18\x01 \x01(\v2#.testsystem.v1.entities.TestCaseRunR\btestCase\"W\n" +
	"\x13TestEndEventRequest\x12@\n" +
	"\ttest_case\x18\x01 \x01(\v2#.testsystem.v1.entities.TestCaseRunR\btestCase\"L\n" +
	"\x15StepBeginEventRequest\x123\n" +
	"\x04step\x18\x01 \x01(\v2\x1f.testsystem.v1.entities.StepRunR\x04step\"J\n" +
	"\x13StepEndEventRequest\x123\n" +
	"\x04step\x18\x01 \x01(\v2\x1f.testsystem.v1.entities.StepRunR\x04step\"\x91\x02\n" +
	"\x17TestFailureEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12'\n" +
	"\x0ffailure_message\x18\x02 \x01(\tR\x0efailureMessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x01(\tR\n" +
	"stackTrace\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12B\n" +
	"\vattachments\x18\x05 \x03(\v2 .testsystem.v1.common.AttachmentR\vattachments\x12\x15\n" +
	"\x06run_id\x18\x06 \x01(\tR\x05runId\"\x8b\x02\n" +
	"\x15TestErrorEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x01(\tR\n" +
	"stackTrace\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12B\n" +
	"\vattachments\x18\x05 \x03(\v2 .testsystem.v1.common.AttachmentR\vattachments\x12\x15\n" +
	"\x06run_id\x18\x06 \x01(\tR\x05runId\"\xc3\x01\n" +
	"\x14StdErrorEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x10test_case_run_id\x18\x04 \x01(\tR\rtestCaseRunId\x12\x15\n" +
	"\x06run_id\x18\x05 \x01(\tR\x05runId\"\xc4\x01\n" +
	"\x15StdOutputEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12'\n" +
	"\x10test_case_run_id\x18\x04 \x01(\tR\rtestCaseRunId\x12\x15\n" +
	"\x06run_id\x18\x05 \x01(\tR\x05runId\"T\n" +
	"\x16SuiteBeginEventRequest\x12:\n" +
	"\x05suite\x18\x01 \x01(\v2$.testsystem.v1.entities.TestSuiteRunR\x05suite\"R\n" +
	"\x14SuiteEndEventRequest\x12:\n" +
	"\x05suite\x18\x01 \x01(\v2$.testsystem.v1.entities.TestSuiteRunR\x05suite\"n\n" +
	"\x15HeartbeatEventRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc8\x02\n" +
	"\x1aReportRunStartEventRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12E\n" +
	"\vtest_suites\x18\x02 \x03(\v2$.testsystem.v1.entities.TestSuiteRunR\n" +
	"testSuites\x12\x1f\n" +
	"\vtotal_tests\x18\x03 \x01(\x05R\n" +
	"totalTests\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12Z\n" +
	"\bmetadata\x18\x05 \x03(\v2>.testsystem.v1.events.ReportRunStartEventRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x16TestRunEndEventRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12C\n" +
	"\ffinal_status\x18\x02 \x01(\x0e2 .testsystem.v1.common.TestStatusR\vfinalStatus\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bdurationB`\n" +
	"%com.stanterprise.testsystem.v1.eventsP\x01Z5github.com/stanterprise/proto-go/testsystem/v1/eventsb\x06proto3"

var (
	file_testsystem_v1_events_events_proto_rawDescOnce sync.Once
	file_testsystem_v1_events_events_proto_rawDescData []byte
)

func file_testsystem_v1_events_events_proto_rawDescGZIP() []byte {
	file_testsystem_v1_events_events_proto_rawDescOnce.Do(func() {
		file_testsystem_v1_events_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testsystem_v1_events_events_proto_rawDesc), len(file_testsystem_v1_events_events_proto_rawDesc)))
	})
	return file_testsystem_v1_events_events_proto_rawDescData
}

var file_testsystem_v1_events_events_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_testsystem_v1_events_events_proto_goTypes = []any{
	(*TestBeginEventRequest)(nil),      // 0: testsystem.v1.events.TestBeginEventRequest
	(*TestEndEventRequest)(nil),        // 1: testsystem.v1.events.TestEndEventRequest
	(*StepBeginEventRequest)(nil),      // 2: testsystem.v1.events.StepBeginEventRequest
	(*StepEndEventRequest)(nil),        // 3: testsystem.v1.events.StepEndEventRequest
	(*TestFailureEventRequest)(nil),    // 4: testsystem.v1.events.TestFailureEventRequest
	(*TestErrorEventRequest)(nil),      // 5: testsystem.v1.events.TestErrorEventRequest
	(*StdErrorEventRequest)(nil),       // 6: testsystem.v1.events.StdErrorEventRequest
	(*StdOutputEventRequest)(nil),      // 7: testsystem.v1.events.StdOutputEventRequest
	(*SuiteBeginEventRequest)(nil),     // 8: testsystem.v1.events.SuiteBeginEventRequest
	(*SuiteEndEventRequest)(nil),       // 9: testsystem.v1.events.SuiteEndEventRequest
	(*HeartbeatEventRequest)(nil),      // 10: testsystem.v1.events.HeartbeatEventRequest
	(*ReportRunStartEventRequest)(nil), // 11: testsystem.v1.events.ReportRunStartEventRequest
	(*TestRunEndEventRequest)(nil),     // 12: testsystem.v1.events.TestRunEndEventRequest
	nil,                                // 13: testsystem.v1.events.ReportRunStartEventRequest.MetadataEntry
	(*entities.TestCaseRun)(nil),       // 14: testsystem.v1.entities.TestCaseRun
	(*entities.StepRun)(nil),           // 15: testsystem.v1.entities.StepRun
	(*timestamppb.Timestamp)(nil),      // 16: google.protobuf.Timestamp
	(*common.Attachment)(nil),          // 17: testsystem.v1.common.Attachment
	(*entities.TestSuiteRun)(nil),      // 18: testsystem.v1.entities.TestSuiteRun
	(common.TestStatus)(0),             // 19: testsystem.v1.common.TestStatus
	(*durationpb.Duration)(nil),        // 20: google.protobuf.Duration
}
var file_testsystem_v1_events_events_proto_depIdxs = []int32{
	14, // 0: testsystem.v1.events.TestBeginEventRequest.test_case:type_name -> testsystem.v1.entities.TestCaseRun
	14, // 1: testsystem.v1.events.TestEndEventRequest.test_case:type_name -> testsystem.v1.entities.TestCaseRun
	15, // 2: testsystem.v1.events.StepBeginEventRequest.step:type_name -> testsystem.v1.entities.StepRun
	15, // 3: testsystem.v1.events.StepEndEventRequest.step:type_name -> testsystem.v1.entities.StepRun
	16, // 4: testsystem.v1.events.TestFailureEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	17, // 5: testsystem.v1.events.TestFailureEventRequest.attachments:type_name -> testsystem.v1.common.Attachment
	16, // 6: testsystem.v1.events.TestErrorEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	17, // 7: testsystem.v1.events.TestErrorEventRequest.attachments:type_name -> testsystem.v1.common.Attachment
	16, // 8: testsystem.v1.events.StdErrorEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	16, // 9: testsystem.v1.events.StdOutputEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	18, // 10: testsystem.v1.events.SuiteBeginEventRequest.suite:type_name -> testsystem.v1.entities.TestSuiteRun
	18, // 11: testsystem.v1.events.SuiteEndEventRequest.suite:type_name -> testsystem.v1.entities.TestSuiteRun
	16, // 12: testsystem.v1.events.HeartbeatEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	18, // 13: testsystem.v1.events.ReportRunStartEventRequest.test_suites:type_name -> testsystem.v1.entities.TestSuiteRun
	13, // 14: testsystem.v1.events.ReportRunStartEventRequest.metadata:type_name -> testsystem.v1.events.ReportRunStartEventRequest.MetadataEntry
	19, // 15: testsystem.v1.events.TestRunEndEventRequest.final_status:type_name -> testsystem.v1.common.TestStatus
	16, // 16: testsystem.v1.events.TestRunEndEventRequest.start_time:type_name -> google.protobuf.Timestamp
	20, // 17: testsystem.v1.events.TestRunEndEventRequest.duration:type_name -> google.protobuf.Duration
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_testsystem_v1_events_events_proto_init() }
func file_testsystem_v1_events_events_proto_init() {
	if File_testsystem_v1_events_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testsystem_v1_events_events_proto_rawDesc), len(file_testsystem_v1_events_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testsystem_v1_events_events_proto_goTypes,
		DependencyIndexes: file_testsystem_v1_events_events_proto_depIdxs,
		MessageInfos:      file_testsystem_v1_events_events_proto_msgTypes,
	}.Build()
	File_testsystem_v1_events_events_proto = out.File
	file_testsystem_v1_events_events_proto_goTypes = nil
	file_testsystem_v1_events_events_proto_depIdxs = nil
}
