// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: testsystem/v1/events/events.proto

package events

import (
	common "github.com/stanterprise/proto-go/testsystem/v1/common"
	entities "github.com/stanterprise/proto-go/testsystem/v1/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestBeginEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestCase      *entities.TestCaseRun  `protobuf:"bytes,1,opt,name=test_case,json=testCase,proto3" json:"test_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestBeginEventRequest) Reset() {
	*x = TestBeginEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestBeginEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestBeginEventRequest) ProtoMessage() {}

func (x *TestBeginEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestBeginEventRequest.ProtoReflect.Descriptor instead.
func (*TestBeginEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{0}
}

func (x *TestBeginEventRequest) GetTestCase() *entities.TestCaseRun {
	if x != nil {
		return x.TestCase
	}
	return nil
}

type TestEndEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestCase      *entities.TestCaseRun  `protobuf:"bytes,1,opt,name=test_case,json=testCase,proto3" json:"test_case,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestEndEventRequest) Reset() {
	*x = TestEndEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestEndEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEndEventRequest) ProtoMessage() {}

func (x *TestEndEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEndEventRequest.ProtoReflect.Descriptor instead.
func (*TestEndEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{1}
}

func (x *TestEndEventRequest) GetTestCase() *entities.TestCaseRun {
	if x != nil {
		return x.TestCase
	}
	return nil
}

type StepBeginEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          *entities.StepRun      `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepBeginEventRequest) Reset() {
	*x = StepBeginEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepBeginEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepBeginEventRequest) ProtoMessage() {}

func (x *StepBeginEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepBeginEventRequest.ProtoReflect.Descriptor instead.
func (*StepBeginEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{2}
}

func (x *StepBeginEventRequest) GetStep() *entities.StepRun {
	if x != nil {
		return x.Step
	}
	return nil
}

type StepEndEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          *entities.StepRun      `protobuf:"bytes,1,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepEndEventRequest) Reset() {
	*x = StepEndEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepEndEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEndEventRequest) ProtoMessage() {}

func (x *StepEndEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEndEventRequest.ProtoReflect.Descriptor instead.
func (*StepEndEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{3}
}

func (x *StepEndEventRequest) GetStep() *entities.StepRun {
	if x != nil {
		return x.Step
	}
	return nil
}

type TestFailureEventRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TestId         string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	FailureMessage string                 `protobuf:"bytes,2,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	StackTrace     string                 `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attachments    []*common.Attachment   `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestFailureEventRequest) Reset() {
	*x = TestFailureEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestFailureEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestFailureEventRequest) ProtoMessage() {}

func (x *TestFailureEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestFailureEventRequest.ProtoReflect.Descriptor instead.
func (*TestFailureEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{4}
}

func (x *TestFailureEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestFailureEventRequest) GetFailureMessage() string {
	if x != nil {
		return x.FailureMessage
	}
	return ""
}

func (x *TestFailureEventRequest) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *TestFailureEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TestFailureEventRequest) GetAttachments() []*common.Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type TestErrorEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StackTrace    string                 `protobuf:"bytes,3,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Attachments   []*common.Attachment   `protobuf:"bytes,5,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestErrorEventRequest) Reset() {
	*x = TestErrorEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestErrorEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestErrorEventRequest) ProtoMessage() {}

func (x *TestErrorEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestErrorEventRequest.ProtoReflect.Descriptor instead.
func (*TestErrorEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{5}
}

func (x *TestErrorEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *TestErrorEventRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TestErrorEventRequest) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *TestErrorEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TestErrorEventRequest) GetAttachments() []*common.Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type StdErrorEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdErrorEventRequest) Reset() {
	*x = StdErrorEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdErrorEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdErrorEventRequest) ProtoMessage() {}

func (x *StdErrorEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdErrorEventRequest.ProtoReflect.Descriptor instead.
func (*StdErrorEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{6}
}

func (x *StdErrorEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *StdErrorEventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StdErrorEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type StdOutputEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestId        string                 `protobuf:"bytes,1,opt,name=test_id,json=testId,proto3" json:"test_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StdOutputEventRequest) Reset() {
	*x = StdOutputEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StdOutputEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StdOutputEventRequest) ProtoMessage() {}

func (x *StdOutputEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StdOutputEventRequest.ProtoReflect.Descriptor instead.
func (*StdOutputEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{7}
}

func (x *StdOutputEventRequest) GetTestId() string {
	if x != nil {
		return x.TestId
	}
	return ""
}

func (x *StdOutputEventRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StdOutputEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SuiteBeginEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suite         *entities.TestSuiteRun `protobuf:"bytes,1,opt,name=suite,proto3" json:"suite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuiteBeginEventRequest) Reset() {
	*x = SuiteBeginEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuiteBeginEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuiteBeginEventRequest) ProtoMessage() {}

func (x *SuiteBeginEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuiteBeginEventRequest.ProtoReflect.Descriptor instead.
func (*SuiteBeginEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{8}
}

func (x *SuiteBeginEventRequest) GetSuite() *entities.TestSuiteRun {
	if x != nil {
		return x.Suite
	}
	return nil
}

type SuiteEndEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suite         *entities.TestSuiteRun `protobuf:"bytes,1,opt,name=suite,proto3" json:"suite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuiteEndEventRequest) Reset() {
	*x = SuiteEndEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuiteEndEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuiteEndEventRequest) ProtoMessage() {}

func (x *SuiteEndEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuiteEndEventRequest.ProtoReflect.Descriptor instead.
func (*SuiteEndEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{9}
}

func (x *SuiteEndEventRequest) GetSuite() *entities.TestSuiteRun {
	if x != nil {
		return x.Suite
	}
	return nil
}

type HeartbeatEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"` // Identifier for the source sending the heartbeat
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatEventRequest) Reset() {
	*x = HeartbeatEventRequest{}
	mi := &file_testsystem_v1_events_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatEventRequest) ProtoMessage() {}

func (x *HeartbeatEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testsystem_v1_events_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatEventRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatEventRequest) Descriptor() ([]byte, []int) {
	return file_testsystem_v1_events_events_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatEventRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *HeartbeatEventRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_testsystem_v1_events_events_proto protoreflect.FileDescriptor

const file_testsystem_v1_events_events_proto_rawDesc = "" +
	"\n" +
	"!testsystem/v1/events/events.proto\x12\x14testsystem.v1.events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!testsystem/v1/common/common.proto\x1a&testsystem/v1/entities/test_case.proto\x1a'testsystem/v1/entities/test_suite.proto\"Y\n" +
	"\x15TestBeginEventRequest\x12@\n" +
	"\ttest_case\x18\x01 \x01(\v2#.testsystem.v1.entities.TestCaseRunR\btestCase\"W\n" +
	"\x13TestEndEventRequest\x12@\n" +
	"\ttest_case\x18\x01 \x01(\v2#.testsystem.v1.entities.TestCaseRunR\btestCase\"L\n" +
	"\x15StepBeginEventRequest\x123\n" +
	"\x04step\x18\x01 \x01(\v2\x1f.testsystem.v1.entities.StepRunR\x04step\"J\n" +
	"\x13StepEndEventRequest\x123\n" +
	"\x04step\x18\x01 \x01(\v2\x1f.testsystem.v1.entities.StepRunR\x04step\"\xfa\x01\n" +
	"\x17TestFailureEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12'\n" +
	"\x0ffailure_message\x18\x02 \x01(\tR\x0efailureMessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x01(\tR\n" +
	"stackTrace\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12B\n" +
	"\vattachments\x18\x05 \x03(\v2 .testsystem.v1.common.AttachmentR\vattachments\"\xf4\x01\n" +
	"\x15TestErrorEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vstack_trace\x18\x03 \x01(\tR\n" +
	"stackTrace\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12B\n" +
	"\vattachments\x18\x05 \x03(\v2 .testsystem.v1.common.AttachmentR\vattachments\"\x83\x01\n" +
	"\x14StdErrorEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x84\x01\n" +
	"\x15StdOutputEventRequest\x12\x17\n" +
	"\atest_id\x18\x01 \x01(\tR\x06testId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"T\n" +
	"\x16SuiteBeginEventRequest\x12:\n" +
	"\x05suite\x18\x01 \x01(\v2$.testsystem.v1.entities.TestSuiteRunR\x05suite\"R\n" +
	"\x14SuiteEndEventRequest\x12:\n" +
	"\x05suite\x18\x01 \x01(\v2$.testsystem.v1.entities.TestSuiteRunR\x05suite\"n\n" +
	"\x15HeartbeatEventRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB`\n" +
	"%com.stanterprise.testsystem.v1.eventsP\x01Z5github.com/stanterprise/proto-go/testsystem/v1/eventsb\x06proto3"

var (
	file_testsystem_v1_events_events_proto_rawDescOnce sync.Once
	file_testsystem_v1_events_events_proto_rawDescData []byte
)

func file_testsystem_v1_events_events_proto_rawDescGZIP() []byte {
	file_testsystem_v1_events_events_proto_rawDescOnce.Do(func() {
		file_testsystem_v1_events_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testsystem_v1_events_events_proto_rawDesc), len(file_testsystem_v1_events_events_proto_rawDesc)))
	})
	return file_testsystem_v1_events_events_proto_rawDescData
}

var file_testsystem_v1_events_events_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_testsystem_v1_events_events_proto_goTypes = []any{
	(*TestBeginEventRequest)(nil),   // 0: testsystem.v1.events.TestBeginEventRequest
	(*TestEndEventRequest)(nil),     // 1: testsystem.v1.events.TestEndEventRequest
	(*StepBeginEventRequest)(nil),   // 2: testsystem.v1.events.StepBeginEventRequest
	(*StepEndEventRequest)(nil),     // 3: testsystem.v1.events.StepEndEventRequest
	(*TestFailureEventRequest)(nil), // 4: testsystem.v1.events.TestFailureEventRequest
	(*TestErrorEventRequest)(nil),   // 5: testsystem.v1.events.TestErrorEventRequest
	(*StdErrorEventRequest)(nil),    // 6: testsystem.v1.events.StdErrorEventRequest
	(*StdOutputEventRequest)(nil),   // 7: testsystem.v1.events.StdOutputEventRequest
	(*SuiteBeginEventRequest)(nil),  // 8: testsystem.v1.events.SuiteBeginEventRequest
	(*SuiteEndEventRequest)(nil),    // 9: testsystem.v1.events.SuiteEndEventRequest
	(*HeartbeatEventRequest)(nil),   // 10: testsystem.v1.events.HeartbeatEventRequest
	(*entities.TestCaseRun)(nil),    // 11: testsystem.v1.entities.TestCaseRun
	(*entities.StepRun)(nil),        // 12: testsystem.v1.entities.StepRun
	(*timestamppb.Timestamp)(nil),   // 13: google.protobuf.Timestamp
	(*common.Attachment)(nil),       // 14: testsystem.v1.common.Attachment
	(*entities.TestSuiteRun)(nil),   // 15: testsystem.v1.entities.TestSuiteRun
}
var file_testsystem_v1_events_events_proto_depIdxs = []int32{
	11, // 0: testsystem.v1.events.TestBeginEventRequest.test_case:type_name -> testsystem.v1.entities.TestCaseRun
	11, // 1: testsystem.v1.events.TestEndEventRequest.test_case:type_name -> testsystem.v1.entities.TestCaseRun
	12, // 2: testsystem.v1.events.StepBeginEventRequest.step:type_name -> testsystem.v1.entities.StepRun
	12, // 3: testsystem.v1.events.StepEndEventRequest.step:type_name -> testsystem.v1.entities.StepRun
	13, // 4: testsystem.v1.events.TestFailureEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	14, // 5: testsystem.v1.events.TestFailureEventRequest.attachments:type_name -> testsystem.v1.common.Attachment
	13, // 6: testsystem.v1.events.TestErrorEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	14, // 7: testsystem.v1.events.TestErrorEventRequest.attachments:type_name -> testsystem.v1.common.Attachment
	13, // 8: testsystem.v1.events.StdErrorEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	13, // 9: testsystem.v1.events.StdOutputEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	15, // 10: testsystem.v1.events.SuiteBeginEventRequest.suite:type_name -> testsystem.v1.entities.TestSuiteRun
	15, // 11: testsystem.v1.events.SuiteEndEventRequest.suite:type_name -> testsystem.v1.entities.TestSuiteRun
	13, // 12: testsystem.v1.events.HeartbeatEventRequest.timestamp:type_name -> google.protobuf.Timestamp
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_testsystem_v1_events_events_proto_init() }
func file_testsystem_v1_events_events_proto_init() {
	if File_testsystem_v1_events_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testsystem_v1_events_events_proto_rawDesc), len(file_testsystem_v1_events_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testsystem_v1_events_events_proto_goTypes,
		DependencyIndexes: file_testsystem_v1_events_events_proto_depIdxs,
		MessageInfos:      file_testsystem_v1_events_events_proto_msgTypes,
	}.Build()
	File_testsystem_v1_events_events_proto = out.File
	file_testsystem_v1_events_events_proto_goTypes = nil
	file_testsystem_v1_events_events_proto_depIdxs = nil
}
